@startuml
autonumber
actor "Responsavel de Recursos Humanos" as UNR

activate UNR
UNR -> ":Sistema" : Pretende especificar um novo colaborador a partir de um ficheiro
activate ":Sistema"
":Sistema" --> UNR : pede para o ficheiro ser inserido
deactivate ":Sistema"


UNR -> ":Sistema" : introduz o ficheiro
activate ":Sistema"
":Sistema" --> UNR : operação bem sucedida
deactivate ":Sistema"

deactivate UNR
@enduml