@startuml

hide footbox

actor Bootstrap as act
actor BootstrapController as ct
actor Utilizador as ut
actor TipoUtilizador as tp
actor UtilizadorRepo as utRep

activate act
act->ct :initiate()
activate ct
ct -> ut : defaultUt()
loop for each type
activate ut
ut->tp: type = ADMIN
activate tp
deactivate tp
ut->ut: id = 1
ut->ut: email = example@example.com
ut->ut: password = example
ut->utRep: add(user)
activate utRep
deactivate utRep
deactivate ut

end loop
deactivate ct
deactivate act
@enduml