@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

class ConsultarTarefasUI <<presentation>>
class ConsultarTarefasController <<application>>
class PersistenceContext <<persistence>>
class RepositoryFactory <<factory>>
class ServicoRepository <<repository>>
class ColaboradorRepository <<repository>>


ConsultarTarefasUI --> ConsultarTarefasController
ConsultarTarefasUI : doShow()
ConsultarTarefasUI : listServicos()
ConsultarTarefasUI : tarefasPendentes(fluxo, colab)
ConsultarTarefasUI : getFluxo()
ConsultarTarefasUI : getUser()

ConsultarTarefasController : tarefasPendentes(fluxo, colab)
ConsultarTarefasController : getFluxo(servico)

ConsultarTarefasController --> ServicoRepository
ConsultarTarefasController --> ColaboradorRepository
ConsultarTarefasController --> PersistenceContext
PersistenceContext --> RepositoryFactory

RepositoryFactory --> ServicoRepository
RepositoryFactory --> ColaboradorRepository

@enduml