@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

class EspecificarServicoController <<application>>
class "Criticidade" as Criticidade <<domain>>
class "Prioridade" as Prioridade <<domain>>
class "Data" as DataLimite <<domain>>
class "EstadoAtividade" as EstadoAtividade <<domain>>
class "AtividadeAutomatica" as AtividadeAutomatica <<domain>>


EspecificarServicoController --> Criticidade
EspecificarServicoController --> Prioridade
EspecificarServicoController --> DataLimite
EspecificarServicoController --> EstadoAtividade
EspecificarServicoController --> AtividadeAutomatica


Criticidade : criticidade = create()
Prioridade : prio = create()
DataLimite : data = create()
EstadoAtividade : estado = create()
AtividadeAutomatica : create = (criticidade, prio, data, estado)


@enduml
