title SD - Desenvolver a componente representativa de uma tarefa automática

@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false


control EspecificarServicoController as Controller <<application>>
participant "Criticidade" as Criticidade <<domain>>
participant "Prioridade" as Prioridade <<domain>>
participant "Data" as DataLimite <<domain>>
participant "EstadoAtividade" as EstadoAtividade <<domain>>
participant "AtividadeAutomatica" as AtividadeAutomatica <<domain>>

Controller -> Criticidade: criticidade  = create()
    activate Criticidade
    deactivate Criticidade
Controller -> Prioridade: prio  = create()
    activate Prioridade
    deactivate Prioridade
Controller -> DataLimite: data  = create()
    activate DataLimite
    deactivate DataLimite
Controller -> EstadoAtividade: estado  = create()
    activate EstadoAtividade
    deactivate EstadoAtividade
Controller -> AtividadeAutomatica: aa  = create(criticidade, prio, data, estado)
    activate AtividadeAutomatica
    deactivate AtividadeAutomatica
deactivate Controller


@enduml
