@startuml

hide footbox

actor RRH as ACT

participant "System" as SYS

ACT->SYS: Inicia o processo de remoção/associação de um colaborador a uma equipa
activate ACT
activate SYS
SYS->ACT: Pede nome/ID de equipa
deactivate SYS
ACT->SYS: Introduz nome/ID de equipa
activate SYS
SYS->ACT: Mostra informação da equipa
deactivate SYS
ACT->SYS: Seleciona a opção de "Gestão de Equipa"
activate SYS
SYS->ACT: Mostra composição atual da equipa
deactivate SYS
ACT->SYS: Seleciona a opção de adição/remoção de membro
activate SYS
SYS->ACT: Solicita nome/ID do colaborador a adicionar/remover
deactivate SYS
ACT->SYS: Introduz nome/ID do colaborador a adicionar/remover
activate SYS
SYS->ACT: Operação bem sucedida
deactivate SYS
deactivate ACT

@enduml