#!/bin/bash
STOREPASS="forgotten"
for ENT in server_E motor ; do
 rm -f ${ENT}.jks ${ENT}.pem
 echo -e "${ENT}\nDEI\nISEP\nPORTO\nPORTO\nPT\nyes" | keytool -genkey -v -alias ${ENT} -keyalg RSA -keysize 2048 \
	-validity 365 -keystore ${ENT}.jks -storepass ${STOREPASS}
 keytool -exportcert -alias ${ENT} -keystore ${ENT}.jks -storepass ${STOREPASS} -rfc -file ${ENT}.pem
done
####
echo "Creating trust relations"
### IMPORTING TRUSTED CERTIFICATES
### (The server trusts all clients except for client4_E)
### (Every client trusts server_E)
for ENT in motor ; do
 echo "yes"|keytool -import -alias ${ENT} -keystore server_E.jks -file ${ENT}.pem -storepass ${STOREPASS}
 echo "yes"|keytool -import -alias server_E -keystore ${ENT}.jks -file server_E.pem -storepass ${STOREPASS}
done
echo "yes"|keytool -import -alias server_E -keystore client4_E.jks -file server_E.pem -storepass ${STOREPASS}
echo "############################################################################"
keytool -list -keystore server_E.jks -storepass ${STOREPASS}
#######
