@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

class ListCatalogoServicoUI <<presentation>>
class ListCatalogoServicoController <<application>>
class PersistenceContext <<persistence>>
class RepositoryFactory <<factory>>
class CatalogoRepository <<repository>>
class ServicoRepository <<repository>>


ListCatalogoServicoUI --> ListCatalogoServicoController
ListCatalogoServicoController : listCatalogo()
ListCatalogoServicoController : listServico()

ListCatalogoServicoController : findCatalogos(titulo, keywords)

ListCatalogoServicoController --> CatalogoRepository
ListCatalogoServicoController --> ServicoRepository
ListCatalogoServicoController --> PersistenceContext
PersistenceContext : repositories()
ListCatalogoServicoController --> RepositoryFactory
RepositoryFactory : catalogos()
RepositoryFactory : servicos()

CatalogoRepository : findCatalogos(titulo)
CatalogoRepository : findAllServico(listCatalogo)

ServicoRepository : findServico(listTotalServico, keywords, titulo)
@enduml
