@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

participant EspecificaServicoCTRL as Controller <<application>>
participant Criticidade as Criticidade <<domain>>
participant Prioridade as Prioridade <<domain>>
participant Data as Data <<domain>>
participant EstadoAtividade as EstadoAtividade <<domain>>
participant Decisao as Decisao <<domain>>
participant Comentario as Comentario <<domain>>
participant AtividadeManual as AtividadeManual <<domain>>

    
      Controller -> Criticidade: crit = create()
    activate Controller
    activate Criticidade
    deactivate Criticidade
      Controller -> Prioridade: prio = create()
    activate Prioridade
    deactivate Prioridade
      Controller -> Data: data = create()
    activate Data
    deactivate Data
      Controller -> EstadoAtividade: estado = create()
    deactivate EstadoAtividade
    deactivate EstadoAtividade
      Controller -> Decisao: des = create()
    deactivate Decisao
    deactivate Decisao
      Controller -> Comentario: coment = create()
    deactivate Comentario
    deactivate Comentario
      Controller -> AtividadeManual: create(crit,prio,data,estado,colab,des,coment)
    activate AtividadeManual
    deactivate AtividadeManual
    deactivate Controller

@enduml