@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

class LerFicheiroColaboradorUI <<presentation>>
class LerFicheiroColaboradorController <<application>>
class LerFicheiroColaborador <<domain>>
class Colaborador <<domain>>
class UserController <<presentation>>>
class ColaboradorRepository <<repository>>
class User <<repository>>


LerFicheiroColaboradorUI --> LerFicheiroColaboradorController : theController

LerFicheiroColaboradorController -> LerFicheiroColaborador
LerFicheiroColaboradorController -> UserController
LerFicheiroColaboradorController -> ColaboradorRepository
LerFicheiroColaboradorController -> Colaborador
LerFicheiroColaboradorController -> User

Colaborador : new Colaborador(numMecanografico,nomeCurto,nomeCompleto,dataNascimento,localResidencia,endereco,contacto)

LerFicheiroColaborador : lerDados()

ColaboradorRepository : save(colab)

User : save()

LerFicheiroColaboradorController : lerDados()

UserController : addUser(username,password,firstname,lastName,endereco,set)

@enduml