@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

Actor "Responsavel de Recursos Humanos" as Actor
participant LerFicheiroColaboradorUI as UI <<presentation>>
participant LerFicheiroColaboradorController as Controller <<application>>
participant LerFicheiroColaborador as LerFicheiroColaborador <<utils>>
participant PersistenceContext as Persistence <<persistence>>
participant RepositoryFactory as Factory <<factory>>
participant Colaborador as Colaborador <<Domain>>
participant UserController as UserController <<Domain>>
database ColaboradorRepository as CRepository <<repository>>
database User as User <<repository>>


activate Actor
      Actor -> UI: Insere o ficheiro
    activate UI
      UI -> Controller: create
    activate Controller
      Controller -> LerFicheiroColaborador: lerDados()
    activate LerFicheiroColaborador
    deactivate
      Controller -> UserController: addUser(username, password, firstName, lastName, endereco, set)
    activate UserController
      UserController -> User : save()
    deactivate UserController
      Controller -> Colaborador: colab = new Colaborador()
    activate Colaborador
    deactivate Colaborador
      Controller -> Persistence: repositories()
    activate Persistence
      Persistence -> Factory: create
    activate Factory
      Factory -> CRepository: create
    activate CRepository
    deactivate CRepository
    deactivate Factory
    deactivate Persistence
      Controller -> CRepository: save(colab)
    activate CRepository
    deactivate CRepository
    deactivate LerFicheiroColaborador
    deactivate Controller
    deactivate UI

deactivate Actor
@enduml