skinparam defaultFontName FG Virgil
skinparam shadowing false

Actor "Responsavel de Recursos Humanos" as Actor
participant EspecificarColaboradorUI as UI <<presentation>>
participant EspecificarColaboradorController as Controller <<application>>
participant PersistenceContext as Persistence <<persistence>>
participant RepositoryFactory as Factory <<factory>>
participant Colaborador as Colaborador <<Domain>>
participant AddUserController as UserController <<application>>
participant RandomRawPassword as RandomRawPassword <<Domain>>
database ColaboradorRepository as CRepository <<repository>>
database SystemUser as URepository <<repository>>


activate Actor
      Actor -> UI: Insere os dados relativos ao colaborador
    activate UI
      UI -> Controller: geraPassword()
    activate Controller
      Controller->RandomRawPassword: toString()
    activate RandomRawPassword
    deactivate RandomRawPassword
      Controller-->UI: password
    deactivate Controller
      UI -> Controller: novoUtilizador(username, password, firstName, lastName, endereco)
    activate Controller
      Controller->UserController: addUser(username, password, firstName, lastName, endereco, set)
    activate UserController
    deactivate UserController
    deactivate Controller
      UI -> Controller: novoColaborador(numMecanografico, nomeCurto, nomeCompleto, dataNascimento, localResidencia, endereco, contacto)
    activate Controller 
      Controller -> Colaborador: colab = new Colaborador()
    activate Colaborador
    deactivate Colaborador
    activate CRepository
      Controller -> CRepository: save(colab)
    deactivate CRepository
    deactivate Controller
    deactivate UI

deactivate Actor
@enduml