skinparam defaultFontName FG Virgil
skinparam shadowing false

Actor "Responsavel de Recursos Humanos" as Actor
participant EspecificarColaboradorUI as UI <<presentation>>
participant EspecificarColaboradorController as Controller <<application>>
participant PersistenceContext as Persistence <<persistence>>
participant RepositoryFactory as Factory <<factory>>
participant Colaborador as Colaborador <<Domain>>
database FuncaoRepository as FRepository <<repository>>
database EquipaRepository as ERepository <<repository>>
database UtilizadorRepository as CRepository <<repository>>


activate Actor
      Actor -> UI: Insere os dados relativos ao colaborador
    activate UI
      UI -> Controller: create
    activate Controller
      Controller -> Persistence: repositories()
    activate Persistence
      Persistence -> Factory: create
    activate Factory
      Factory -> FRepository: create
    activate FRepository
    deactivate Factory
    deactivate Persistence
      Controller -> FRepository: getFuncoes()
      Controller -> UI: listFuncoes
    deactivate FRepository
    deactivate Controller
      UI -> Actor: Apresenta as funções
    deactivate UI
      Actor -> UI: Seleciona uma função
    activate UI
      UI -> Controller: verificaSuperior(funcao)
    activate Controller 
      Controller -> Persistence: repositories()
    activate Persistence
      Persistence -> Factory: create
    activate Factory
      Factory -> CRepository: create
    activate CRepository
    deactivate Factory
    deactivate Persistence
      Controller -> CRepository: getSuperior()
    deactivate CRepository
      Controller -> UI: superior
    deactivate Controller

    alt se houver superior
      UI -> Controller: novoColaborador(numMecanografico, nomeCurto, nomeCompleto, dataNascimento, localResidencia, endereco, contacto, funcao, superior)
    activate Controller
      Controller -> Colaborador: colab = new Colaborador()
    activate Colaborador
    deactivate Colaborador
    deactivate Controller
    else 
      UI -> Controller: novoColaborador(numMecanografico, nomeCurto, nomeCompleto, dataNascimento, localResidencia, endereco, contacto, funcao)
    activate Controller
      Controller -> Colaborador: colab = new Colaborador()
    activate Colaborador
    deactivate Colaborador
    end
    activate CRepository
      Controller -> CRepository: save(colab)
    deactivate CRepository
      Controller -> Controller: gerarPassword() 
      Controller -> Controller: enviarEmailColaborador()
    deactivate Controller
    deactivate UI

deactivate Actor
@enduml