@startuml use-case-realization.svg

participant Sistema <<client>>

ValidacaoDaemon -> ValidacaoServer : new
loop true
ValidacaoDaemon -> ValidacaoServer: start
Activate ValidacaoServer
ValidacaoServer -> ValidacaoServer: accept

Sistema --> ValidacaoServer

participant HandleClient <<thread>>
activate HandleClient
ValidacaoServer -\ HandleClient: start
deactivate ValidacaoServer
end

HandleClient -> MessageParser:parse
HandleClient -> HandleClient: execute
HandleClient -> MessageBuilder:build

HandleClient --> Sistema
deactivate HandleClient

@enduml