@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

class AtribuirGrauSatisfacaoUI <<presentation>>
class AtribuirGrauSatisfacaoController <<application>>
class PersistenceContext <<persistence>>
class RepositoryFactory <<factory>>
class PedidoRepository <<repository>>
class ColaboradorRepository <<repository>>
class Pedido <<entity>>


AtribuirGrauSatisfacaoUI --> AtribuirGrauSatisfacaoController
AtribuirGrauSatisfacaoUI : doShow()

AtribuirGrauSatisfacaoController : getUser()
AtribuirGrauSatisfacaoController : pedidosPendentes(colab)
AtribuirGrauSatisfacaoController : atribuirGrau(pedido, grau)

AtribuirGrauSatisfacaoController --> PedidoRepository
AtribuirGrauSatisfacaoController --> ColaboradorRepository
AtribuirGrauSatisfacaoController --> PersistenceContext
PersistenceContext --> RepositoryFactory

ColaboradorRepository : getUser()

PedidoRepository --> Pedido
PedidoRepository : pedidosPendentes(colab)

Pedido : atribuirGrau(pedido, grau)

RepositoryFactory --> PedidoRepository
RepositoryFactory --> ColaboradorRepository

@enduml