@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

participant AtribuirGrauSatisfacaoUI as UI <<presentation>>
control AtribuirGrauSatisfacaoController as CTRL <<application>>
participant PersistenceContext as Persistence <<persistence>>
participant RepositoryFactory as Factory <<factory>>
entity Pedido as Ped <<entity>>
database PedidoRepository as PRepository <<repository>>
database ColaboradorRepository as CRepository <<repository>>

activate UI

UI -> UI : doShow()
 note over CTRL: Para efeitos de simplificação do diagrama, não foram representadas todas as classes repository,\n a classe persistence e a classe factory, tendo sido utilizado o procedimento dos casos de uso do sprint anterior
UI -> CTRL: getUser()
    activate CTRL
    CTRL -> CRepository: getUser()
      activate CRepository
      deactivate CRepository
      CTRL -> UI: colab
    deactivate CTRL
    
UI -> CTRL: pedidosPendentes(colab)
    activate CTRL
      CTRL -> PRepository: pedidosPendentes(colab)
      activate PRepository
      deactivate PRepository
      CTRL -> UI: listaPedidos
    deactivate CTRL
loop
UI -> CTRL: atribuirGrau(pedido. grau)
    activate CTRL
      CTRL -> Ped: atribuirGrau(pedido, grau)
      activate Ped
      deactivate Ped
    deactivate CTRL
end
deactivate UI
@enduml

