@startuml
autonumber
actor "Utilizador" as USR

activate USR
USR -> ":System" : pretende transmitir o seu grau de satisfação
activate ":System"
":System" --> USR : devolve a lista de pedidos do colaborador
deactivate ":System"

USR -> ":System" : seleciona o pedido a atribuir o grau
activate ":System"
":System" --> USR : solicita o valor do grau
deactivate ":System"

USR -> ":System" : insere o grau de satisfação
activate ":System"
":System" --> USR : operação bem sucedida
deactivate ":System"

deactivate USR
@enduml
