@startuml
autonumber
actor "Colaborador" as USR

activate USR
USR -> ":Colaborador" : pretende transmitir o seu grau de satisfação
activate ":Colaborador"
":Colaborador" --> USR : devolve a lista de pedidos do colaborador
deactivate ":Colaborador"

USR -> ":Colaborador" : seleciona o pedido a atribuir o grau
activate ":Colaborador"
":Colaborador" --> USR : solicita o valor do grau
deactivate ":Colaborador"

USR -> ":Colaborador" : insere o grau de satisfação
activate ":Colaborador"
":Colaborador" --> USR : operação bem sucedida
deactivate ":Colaborador"

deactivate USR
@enduml
