@startuml

class Bootstrap {
}

class BootstrapController {
   initiate()
}

class Utilizador {
  default()
}

class UtilizadorRep {
  add()
}

interface TipoUtilizador{
    ADMINISTRADOR
    GESTOR_SERVIÇO
    RESPONSAVELRRH
}

Bootstrap .-> BootstrapController
BootstrapController .-> Utilizador
Utilizador ->UtilizadorRep : armazena informação>
Utilizador -> TipoUtilizador : recorre a >

@enduml