title SD - Definir os niveis de criticidade e respetivos objetivos

@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor GSH as Actor
participant DefinirCriticidadeUI as UI <<presentation>>
control DefinirCriticidadeController as Controller <<application>>
participant PersistenceContext as Persistence <<persistence>>
participant RepositoryFactory as Factory <<factory>>
database CriticidadeRepository as CRepository <<repository>>
database ContratoRepository as Repository <<repository>>
participant "Objetivo" as Objetivo <<domain>>
participant "TempoMed" as TempoMed <<domain>>
participant "Cor" as Cor <<domain>>
participant "Etiqueta" as Etiqueta <<domain>>
participant "Escala" as Escala <<domain>>
participant "Designacao" as Designacao <<domain>>
participant "Criticidade" as Criticidade <<domain>>
participant "ContratoSLA" as Contrato <<domain>>



activate Actor
Actor -> UI: pretende definir os niveis de criticidade e respetivos objetivos
activate UI
UI -> Controller: listCriticidade()
    activate Controller
    Controller -> Persistence: repositories()
        activate Persistence
        Persistence --> Factory: create()
            activate Factory
            Factory --> Persistence:
            deactivate Factory
        Persistence --> Controller:
        deactivate Persistence
    Controller -> Factory: criticidade()
        activate Factory
        Factory --> CRepository : create()
            activate CRepository
            deactivate CRepository
        deactivate Factory
    deactivate Controller
        
UI -> Controller: listCatalogo()
    activate Controller
    Controller -> Persistence: repositories()
        activate Persistence
        Persistence --> Factory: create()
            activate Factory
            Factory --> Persistence:
            deactivate Factory
        Persistence --> Controller:
        deactivate Persistence
    Controller -> Factory: catalogo()
        activate Factory
        Factory --> Repository : create()
            activate Repository
            deactivate Repository
        deactivate Factory

    deactivate Controller
    loop para todos os niveis de criticidade
UI --> Actor: requisita a informação de um nivel de criticidade
deactivate UI

Actor -> UI: insere os dados solicitados
activate UI
UI -> Controller:  defineCriticidade(tempoMaximo, tempoMedio, etiqueta, escala, cor, designacao)
    activate Controller
    Controller -> Objetivo: obj  = create(tempoMaximo, tempoMedio)
        activate Objetivo
        deactivate Objetivo
    Controller -> Etiqueta: e  = create(etiqueta)
        activate Etiqueta
        deactivate Etiqueta
    Controller -> Escala: esc  = create(escala)
        activate Escala
        deactivate Escala
    Controller -> Cor: c  = create(cor)
        activate Cor
        deactivate Cor
    Controller -> Designacao: desig  = create(designacao)
        activate Designacao
        deactivate Designacao
    Controller -> Criticidade: nivelCriticidade  = create(obj,e,esc,c,desig)
        activate Criticidade
        deactivate Criticidade
    Controller -> CRepository: save(nivelCriticidade)
        activate CRepository
        deactivate CRepository
    deactivate Controller
    end
UI --> Actor: apresenta o conjunto de niveis de criticidade e solicita designacao do contrato
deactivate UI
Actor -> UI: introduz os dados solicitados
activate UI
UI -> Controller: defineContrato(designacao)
    activate Controller
    Controller -> CRepository: listCriticidade = findAllCriticidade()
        activate CRepository
        deactivate CRepository
    Controller -> Designacao: des = create(designacao)
        activate Designacao
        deactivate Designacao
    Controller -> Contrato: cont = create(des,listCriticidade)
        activate Contrato
        deactivate Contrato
    Controller -> Repository: save(cont)
        activate Repository
        deactivate Repository
    deactivate Controller
UI --> Actor: informa sucesso da operação
deactivate UI
deactivate Actor

@enduml
