@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor GSH as Actor
participant System as System
activate Actor
Actor -> System: pretende definir os niveis de criticidade e respetivos objetivos
activate System
System --> Actor: requisita niveis de criticidade
deactivate System
Actor -> System: insere os dados solicitados
activate System
System --> Actor: apresenta o conjunto de niveis de criticidade e solicita designacao do contrato
deactivate System
Actor -> System: introduz os dados solicitados
activate System
System --> Actor: informa sucesso da operação
deactivate System
deactivate Actor

@enduml