@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

participant CriarEquipaUI as UI <<presentation>>
control CriarEquipaController as CTRL <<application>>
participant PersistenceContext as Persistence <<persistence>>
participant RepositoryFactory as Factory <<factory>>
database EquipaRepository as ERepository <<repository>>
database TipoEquipaRepository as TERepository <<repository>>
database ColaboradorRepository as CRepository <<repository>>
entity Equipa as EQ <<entity>>
entity CodigoUnico as COD <<Value>>
entity Acronimo as AC <<Value>>
entity Designacao as DES <<Value>>

activate UI

UI -> UI : doShow()

UI -> CTRL: listTipos()
    activate CTRL
      CTRL -> Persistence: repositories()
    activate Persistence
      Persistence -> Factory: create()
    activate Factory
      Factory -> TERepository: create()
    activate TERepository
    deactivate Factory
    deactivate Persistence
        deactivate TERepository
      CTRL -> TERepository: findAll()
      activate TERepository
      deactivate TERepository
      CTRL -> UI: listaTipos
    deactivate CTRL

UI -> CTRL: listColab()
    activate CTRL
      CTRL -> Persistence: repositories()
    activate Persistence
      Persistence -> Factory: create()
    activate Factory
      Factory -> CRepository: create()
    activate CRepository
    deactivate Factory
    deactivate Persistence
     deactivate CRepository
      CTRL -> CRepository: findAll()
      activate CRepository
   deactivate CRepository
      CTRL -> UI: listaColab
    deactivate CTRL
    
UI -> CTRL : novaEquipa(cod, acronimo, desig, tipo, responsaveis)
activate CTRL

CTRL->COD :cod = create(cod)
CTRL->AC :acronimo = create(acronimo)
CTRL->DES:desig = create(desig)
		
CTRL -> Persistence: repositories()
        activate Persistence
            Persistence --> Factory: create()
            activate Factory
                Factory --> Persistence:
            
            Persistence --> CTRL:
        deactivate Persistence

            Factory --> ERepository : create()
            deactivate Factory
            
        activate ERepository
            ERepository --> Factory : 
        deactivate ERepository
        
CTRL --> EQ ** : novaEquipa = create(cod, acronimo, desig, tipo, responsaveis)

        CTRL -> ERepository: save(novaEquipa)
        activate ERepository
        deactivate ERepository
        
deactivate CTRL
deactivate UI
@enduml
