@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

participant CumprimentoSlaUI as UI <<presentation>>
control CumprimentoSlaController as CTRL <<application>>
database PedidoRepository as PRepository <<repository>>

activate UI

UI -> UI : doShow()
 note over CTRL: Para efeitos de simplificação do diagrama, não foram representadas todas as classes repository,\n a classe persistence e a classe factory, tendo sido utilizado o procedimento dos casos de uso do sprint B
UI -> CTRL: getAllPedidoConcluido()
    activate CTRL
    CTRL -> PRepository: listaPedidos = getAllPedidoConcluido()
      activate PRepository
      deactivate PRepository
    deactivate CTRL
    
loop para a listaPedidos
UI -> CTRL: getTempoMaximoAprov(pedido)
    activate CTRL
    CTRL -> PRepository: tempoMaxAprov = getTempoMaximoAprov(pedido)
      activate PRepository
      deactivate PRepository
    deactivate CTRL

UI -> CTRL: getTempoMaximoRes(pedido)
    activate CTRL
    CTRL -> PRepository: tempoMaxRes = getTempoMaximoRes(pedido)
      activate PRepository
      deactivate PRepository
    deactivate CTRL

UI -> CTRL: getTarefasDoPedido(pedido)
    activate CTRL
    CTRL -> PRepository: listaAtividades = getTarefasDoPedido(pedido)
      activate PRepository
      deactivate PRepository
    deactivate CTRL

loop para a listaAtividades
UI -> CTRL: getTempoDaTarefa(atividade)
    activate CTRL
    CTRL -> PRepository: tempoTarefa = getTempoDaTarefa(atividade)
      activate PRepository
      deactivate PRepository
    deactivate CTRL
end
end

deactivate UI
@enduml

