@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

class NovoCatalogoUI <<presentation>>
class NovoCatalogoController <<application>>
class Catalogo <<domain>>
class CatalogoRepository <<repository>>
class UtilizadorRepository <<repository>>
class EquipaRepository <<repository>>


NovoCatalogoUI --> NovoCatalogoController : theController

NovoCatalogoController -> ColaboradorRepository
NovoCatalogoController -> CatalogoRepository
NovoCatalogoController -> EquipaRepository
NovoCatalogoController -> Catalogo

NovoCatalogoController : getEquipas()
NovoCatalogoController : novoCatalogo(titulo,descricaoBreve,descricaoCompleta,icone,listEquipas)

Catalogo : Catalogo(titulo,descricaoBreve,descricaoCompleta,icone,listEquipas)

CatalogoRepository : save(cat)

ColaboradorRepository : findAll()

EquipaRepository : listEquipas()

@enduml