@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

class NovoCatalogoUI <<presentation>>
class NovoCatalogoController <<application>>
class Catalogo <<domain>>
class Objetivo <<domain>>
class CatalogoRepository <<repository>>
class UtilizadorRepository <<repository>>
class EquipaRepository <<repository>>


NovoCatalogoUI --> NovoCatalogoController : theController

NovoCatalogoController -> UtilizadorRepository
NovoCatalogoController -> CatalogoRepository
NovoCatalogoController -> EquipaRepository
NovoCatalogoController -> Catalogo
NovoCatalogoController -> Objetivo

NovoCatalogoController : getEquipas ()
NovoCatalogoController : novoObjetivo(tempoMax,tempoMedio)
NovoCatalogoController : novoCatalogo(identificador,titulo,descricaoBreve,descricaoCompleta,icone,listEquipas,obj)
NovoCatalogoController : novoCatalogo(identificador,titulo,descricaoBreve,descricaoCompleta,icone,listEquipas)

Catalogo : Catalogo(identificador,titulo,descricaoBreve,descricaoCompleta,icone,listEquipas)
Catalogo : Catalogo(identificador,titulo,descricaoBreve,descricaoCompleta,icone,listEquipas,obj) 

Objetivo : Objetivo(tempoMax,tempoMedio)

CatalogoRepository : save(cat)

UtilizadorRepository : listColaboradores()

EquipaRepository : listEquipas()

@enduml